project_id = "emaarjwsapuldzvdsite"

[functions.ai-quizzes]
verify_jwt = false

[functions.ai-products]
verify_jwt = false

[functions.trending-feed]
verify_jwt = false

[functions.generate-category-image]
verify_jwt = false
