import type { Dispatch, SetStateAction } from "react";
import { ChevronLeft } from "lucide-react";
import type { SubtypeItem } from "@/data/templateSubtypes";
import MyGoTwoDesktopPage from "@/platform-ui/web/mygotwo/MyGoTwoDesktopPage";
import MyGoTwoWebProductCard from "@/platform-ui/web/mygotwo/MyGoTwoWebProductCard";

interface CardEntry {
  id: string;
  user_id: string;
  card_key: string;
  group_name: string;
  entry_name: string;
  field_values: Record<string, string>;
  image_url?: string | null;
  created_at: string;
  updated_at: string;
}

interface MyGoTwoDesktopCardBrowserProps {
  leafSubtype: SubtypeItem;
  leafSubcategoryName?: string;
  leafCategoryName?: string;
  leafImage: string;
  entries: CardEntry[];
  productGroups: string[];
  activeGroup: string;
  setActiveGroup: Dispatch<SetStateAction<string>>;
  focusedEntryIdByGroup: Record<string, string>;
  setFocusedEntryIdByGroup: Dispatch<SetStateAction<Record<string, string>>>;
  entryNames: Record<string, string>;
  entryDrafts: Record<string, Record<string, string>>;
  entryImages: Record<string, string>;
  resolvedEntryImages: Record<string, string>;
  defaultFieldValues: Record<string, string>;
  saving: boolean;
  newEntryPrefix: string;
  normalizeImageValue: (value?: string | null) => string;
  onBack: () => void;
  onEntryNameChange: (itemId: string, value: string) => void;
  onFieldChange: (itemId: string, fieldLabel: string, value: string) => void;
  onImageChange: (itemId: string, imageUrl: string) => void;
  onSaveEntry: (itemId: string) => void;
  onDeleteEntry: (itemId: string) => void;
  onCreateGroup: () => void;
}

interface DesktopEntryStageItem {
  id: string;
  label: string;
  image: string;
}

function isAutoGeneratedEntryName(name: string | undefined, subtypeName: string) {
  if (!name) return false;
  const escapedSubtypeName = subtypeName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^${escapedSubtypeName}\\s+\\d+$`).test(name.trim());
}

function getDisplayEntryName(name: string | undefined, subtypeName: string) {
  if (!name || isAutoGeneratedEntryName(name, subtypeName)) return "";
  return name;
}

export default function MyGoTwoDesktopCardBrowser({
  leafSubtype,
  leafSubcategoryName,
  leafCategoryName,
  leafImage,
  entries,
  productGroups,
  activeGroup,
  setActiveGroup,
  focusedEntryIdByGroup,
  setFocusedEntryIdByGroup,
  entryNames,
  entryDrafts,
  entryImages,
  resolvedEntryImages,
  defaultFieldValues,
  saving,
  newEntryPrefix,
  normalizeImageValue,
  onBack,
  onEntryNameChange,
  onFieldChange,
  onImageChange,
  onSaveEntry,
  onDeleteEntry,
  onCreateGroup,
}: MyGoTwoDesktopCardBrowserProps) {
  const currentGroup = productGroups.includes(activeGroup) ? activeGroup : productGroups[0] || leafSubtype.name;
  const groupEntries = entries.filter((entry) => entry.group_name === currentGroup);
  const newEntryId = `${newEntryPrefix}::${currentGroup}`;

  const editorItems: DesktopEntryStageItem[] = [
    ...groupEntries.map((entry) => ({
      id: entry.id,
      label: getDisplayEntryName(entryNames[entry.id] || entry.entry_name, leafSubtype.name) || leafSubtype.name,
      image: normalizeImageValue(
        resolvedEntryImages[entryImages[entry.id] || entry.image_url || ""]
        || entryImages[entry.id]
        || entry.image_url,
      ),
    })),
    {
      id: newEntryId,
      label: getDisplayEntryName(entryNames[newEntryId]?.trim(), leafSubtype.name) || leafSubtype.name,
      image: normalizeImageValue(
        resolvedEntryImages[entryImages[newEntryId] || ""]
        || entryImages[newEntryId]
        || leafImage,
      ),
    },
  ];

  const preferredActiveItemId = focusedEntryIdByGroup[currentGroup];
  const activeItemId = editorItems.some((item) => item.id === preferredActiveItemId)
    ? preferredActiveItemId
    : editorItems[0]?.id ?? newEntryId;
  const activeEntry = groupEntries.find((entry) => entry.id === activeItemId) ?? null;
  const activeItemIndex = Math.max(0, editorItems.findIndex((item) => item.id === activeItemId));
  const activeDisplayName = getDisplayEntryName(entryNames[activeItemId] || activeEntry?.entry_name, leafSubtype.name);
  const activeItemName = activeDisplayName || leafSubtype.name;
  const activeItemValues = entryDrafts[activeItemId] || defaultFieldValues;
  const activeItemImage =
    normalizeImageValue(resolvedEntryImages[entryImages[activeItemId] || activeEntry?.image_url || ""])
    || normalizeImageValue(entryImages[activeItemId])
    || normalizeImageValue(activeEntry?.image_url)
    || normalizeImageValue(leafImage)
    || "";
  const visibleStripItems = editorItems.slice(Math.max(0, activeItemIndex - 2), Math.min(editorItems.length, activeItemIndex + 3));

  return (
    <MyGoTwoDesktopPage
      topSlot={
        <button
          type="button"
          aria-label="Go back"
          className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-full border border-white/75 bg-[rgba(255,255,255,0.72)] text-[var(--logo-two-color)] shadow-[0_10px_26px_rgba(20,20,30,0.08)]"
          onClick={onBack}
        >
          <ChevronLeft className="h-5 w-5" />
        </button>
      }
    >
      <div className="grid h-full min-h-0 gap-5 xl:grid-cols-[minmax(560px,1.18fr)_minmax(420px,0.82fr)]">
        <section className="grid min-h-0 grid-rows-[auto_minmax(0,1fr)_auto] rounded-[36px] border border-white/65 bg-[linear-gradient(180deg,rgba(255,255,255,0.42),rgba(255,245,238,0.28))] px-6 pb-6 pt-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.84),0_24px_60px_rgba(20,20,30,0.09)] backdrop-blur-md">
          <div className="flex flex-wrap items-center gap-3">
            {productGroups.map((groupName) => {
              const isActive = groupName === currentGroup;
              const isSyntheticGroup = /^__product_group_\d+$/.test(groupName);
              const label = isSyntheticGroup ? `Group ${groupName.split("_").pop()}` : groupName;

              return (
                <button
                  key={groupName}
                  type="button"
                  className="rounded-full px-4 py-2 text-[13px] transition-all"
                  style={{
                    fontFamily: "'Jost', sans-serif",
                    background: isActive ? "var(--swatch-teal)" : "rgba(255,255,255,0.68)",
                    color: isActive ? "white" : "var(--swatch-teal)",
                    border: isActive ? "1px solid var(--swatch-teal)" : "1px solid rgba(45,104,112,0.18)",
                  }}
                  onClick={() => setActiveGroup(groupName)}
                >
                  {label}
                </button>
              );
            })}
            <button
              type="button"
              className="rounded-full border border-dashed px-4 py-2 text-[13px]"
              style={{ fontFamily: "'Jost', sans-serif", color: "var(--swatch-teal)", borderColor: "rgba(45,104,112,0.32)" }}
              onClick={onCreateGroup}
            >
              + New Group
            </button>
          </div>

          <div className="grid min-h-0 place-items-center py-6">
            <div className="grid w-full max-w-[760px] justify-items-center gap-6">
              <div className="relative flex min-h-[420px] w-full items-center justify-center">
                {editorItems.length > 1 && activeItemIndex > 0 ? (
                  <button
                    type="button"
                    onClick={() => setFocusedEntryIdByGroup((prev) => ({ ...prev, [currentGroup]: editorItems[activeItemIndex - 1].id }))}
                    className="absolute left-0 top-1/2 hidden -translate-y-1/2 lg:block"
                    aria-label="Previous card"
                  >
                    <div className="w-[148px] overflow-hidden rounded-[26px] border border-white/60 bg-white/55 p-2 shadow-[0_16px_34px_rgba(20,20,30,0.12)] backdrop-blur">
                      <div className="aspect-[396/528] overflow-hidden rounded-[20px] bg-[rgba(45,104,112,0.08)]">
                        {editorItems[activeItemIndex - 1].image ? (
                          <img src={editorItems[activeItemIndex - 1].image} alt={editorItems[activeItemIndex - 1].label} className="h-full w-full object-cover" />
                        ) : null}
                      </div>
                    </div>
                  </button>
                ) : null}

                <div className="w-full max-w-[390px]">
                  <div className="overflow-hidden rounded-[34px] border border-white/70 bg-white/72 p-3 shadow-[0_24px_50px_rgba(20,20,30,0.18)] backdrop-blur">
                    <div className="aspect-[396/528] overflow-hidden rounded-[28px] bg-[rgba(45,104,112,0.08)]">
                      {activeItemImage ? (
                        <img src={activeItemImage} alt={activeItemName} className="h-full w-full object-cover" />
                      ) : (
                        <div
                          className="flex h-full items-center justify-center p-8 text-center"
                          style={{ fontFamily: "'Cormorant Garamond', serif", color: "var(--swatch-teal)", fontSize: 34, fontWeight: 700 }}
                        >
                          {activeItemName}
                        </div>
                      )}
                    </div>
                  </div>
                  <div className="mt-4 flex items-center justify-center">
                    <div className="rounded-full border border-white/75 bg-[rgba(255,255,255,0.84)] px-5 py-2 shadow-[0_10px_24px_rgba(20,20,30,0.1)]">
                      <span style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: 20, fontWeight: 700, color: "var(--swatch-teal)" }}>
                        {activeItemName}
                      </span>
                    </div>
                  </div>
                </div>

                {editorItems.length > 1 && activeItemIndex < editorItems.length - 1 ? (
                  <button
                    type="button"
                    onClick={() => setFocusedEntryIdByGroup((prev) => ({ ...prev, [currentGroup]: editorItems[activeItemIndex + 1].id }))}
                    className="absolute right-0 top-1/2 hidden -translate-y-1/2 lg:block"
                    aria-label="Next card"
                  >
                    <div className="w-[148px] overflow-hidden rounded-[26px] border border-white/60 bg-white/55 p-2 shadow-[0_16px_34px_rgba(20,20,30,0.12)] backdrop-blur">
                      <div className="aspect-[396/528] overflow-hidden rounded-[20px] bg-[rgba(45,104,112,0.08)]">
                        {editorItems[activeItemIndex + 1].image ? (
                          <img src={editorItems[activeItemIndex + 1].image} alt={editorItems[activeItemIndex + 1].label} className="h-full w-full object-cover" />
                        ) : null}
                      </div>
                    </div>
                  </button>
                ) : null}
              </div>

              <div className="flex w-full max-w-[700px] items-center justify-center gap-3 overflow-x-auto pb-1">
                {visibleStripItems.map((item) => {
                  const isActive = item.id === activeItemId;
                  return (
                    <button
                      key={item.id}
                      type="button"
                      onClick={() => setFocusedEntryIdByGroup((prev) => ({ ...prev, [currentGroup]: item.id }))}
                      className="shrink-0 rounded-[22px] border p-2 text-left transition-all"
                      style={{
                        width: isActive ? 136 : 118,
                        background: isActive ? "rgba(45,104,112,0.12)" : "rgba(255,255,255,0.72)",
                        borderColor: isActive ? "rgba(45,104,112,0.45)" : "rgba(190,176,160,0.38)",
                        boxShadow: isActive ? "0 12px 26px rgba(45,104,112,0.14)" : "0 8px 18px rgba(20,20,30,0.06)",
                      }}
                    >
                      <div className="aspect-[396/528] overflow-hidden rounded-[18px] bg-[rgba(45,104,112,0.08)]">
                        {item.image ? <img src={item.image} alt={item.label} className="h-full w-full object-cover" /> : null}
                      </div>
                      <div className="pt-2 text-center" style={{ fontFamily: "'Jost', sans-serif", fontSize: 12, color: "var(--swatch-teal)" }}>
                        {item.label}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          </div>

          <div className="flex flex-wrap items-center justify-between gap-4 pt-4">
            <div
              className="text-[22px] leading-none"
              style={{
                color: "rgba(82,110,125,0.72)",
                fontFamily: "'Cormorant Garamond', serif",
              }}
            >
              {saving ? "Saving..." : `Editing: ${activeItemName}`}
            </div>
          </div>
        </section>

        <aside className="flex min-h-0 items-center justify-center pb-4 xl:pb-0">
          <div
            className="w-full max-w-[462px] overflow-hidden rounded-[32px] shadow-[0_18px_34px_rgba(110,117,118,0.22),0_34px_90px_rgba(75,79,79,0.24)]"
            style={{ aspectRatio: "462 / 678" }}
          >
            <MyGoTwoWebProductCard
              subtype={leafSubtype}
              subcategoryName={leafSubcategoryName}
              categoryName={leafCategoryName}
              entryName={activeDisplayName}
              values={activeItemValues}
              imageUrl={activeItemImage}
              saving={saving}
              isEditing={!activeItemId.startsWith(`${newEntryPrefix}::`)}
              onEntryNameChange={(name) => onEntryNameChange(activeItemId, name)}
              onChange={(fieldLabel, value) => onFieldChange(activeItemId, fieldLabel, value)}
              onImageChange={(imageUrl) => onImageChange(activeItemId, imageUrl)}
              onSave={() => onSaveEntry(activeItemId)}
              onDelete={() => onDeleteEntry(activeItemId)}
            />
          </div>
        </aside>
      </div>
    </MyGoTwoDesktopPage>
  );
}
