import type { Dispatch, SetStateAction } from "react";
import { ChevronLeft } from "lucide-react";
import type { SubtypeItem } from "@/data/templateSubtypes";
import MyGoTwoDesktopBrowser from "@/platform-ui/web/mygotwo/MyGoTwoDesktopBrowser";
import type { MyGoTwoWebCoverflowItem } from "@/platform-ui/web/mygotwo/MyGoTwoWebCoverflow";
import MyGoTwoWebProductCard from "@/platform-ui/web/mygotwo/MyGoTwoWebProductCard";

interface CardEntry {
  id: string;
  user_id: string;
  card_key: string;
  group_name: string;
  entry_name: string;
  field_values: Record<string, string>;
  image_url?: string | null;
  created_at: string;
  updated_at: string;
}

interface MyGoTwoDesktopCardBrowserProps {
  leafSubtype: SubtypeItem;
  leafSubcategoryName?: string;
  leafCategoryName?: string;
  leafImage: string;
  entries: CardEntry[];
  productGroups: string[];
  activeGroup: string;
  activeEntryIndexByGroup: Record<string, number>;
  setActiveEntryIndexByGroup: Dispatch<SetStateAction<Record<string, number>>>;
  entryNames: Record<string, string>;
  entryDrafts: Record<string, Record<string, string>>;
  entryImages: Record<string, string>;
  resolvedEntryImages: Record<string, string>;
  defaultFieldValues: Record<string, string>;
  saving: boolean;
  newEntryPrefix: string;
  normalizeImageValue: (value?: string | null) => string;
  onBack: () => void;
  onEntryNameChange: (itemId: string, value: string) => void;
  onFieldChange: (itemId: string, fieldLabel: string, value: string) => void;
  onImageChange: (itemId: string, imageUrl: string) => void;
  onSaveEntry: (itemId: string) => void;
  onDeleteEntry: (itemId: string) => void;
  onCreateGroup: () => void;
}

function isAutoGeneratedEntryName(name: string | undefined, subtypeName: string) {
  if (!name) return false;
  const escapedSubtypeName = subtypeName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^${escapedSubtypeName}\\s+\\d+$`).test(name.trim());
}

function getDisplayEntryName(name: string | undefined, subtypeName: string) {
  if (!name || isAutoGeneratedEntryName(name, subtypeName)) return "";
  return name;
}

export default function MyGoTwoDesktopCardBrowser({
  leafSubtype,
  leafSubcategoryName,
  leafCategoryName,
  leafImage,
  entries,
  productGroups,
  activeGroup,
  activeEntryIndexByGroup,
  setActiveEntryIndexByGroup,
  entryNames,
  entryDrafts,
  entryImages,
  resolvedEntryImages,
  defaultFieldValues,
  saving,
  newEntryPrefix,
  normalizeImageValue,
  onBack,
  onEntryNameChange,
  onFieldChange,
  onImageChange,
  onSaveEntry,
  onDeleteEntry,
  onCreateGroup,
}: MyGoTwoDesktopCardBrowserProps) {
  const currentGroup = productGroups.includes(activeGroup) ? activeGroup : productGroups[0] || leafSubtype.name;
  const groupEntries = entries.filter((entry) => entry.group_name === currentGroup);
  const newEntryId = `${newEntryPrefix}::${currentGroup}`;
  const activeIndex = Math.min(activeEntryIndexByGroup[currentGroup] ?? 0, Math.max(groupEntries.length, 0));
  const activeEntry = groupEntries[activeIndex] ?? null;
  const activeItemId = activeEntry?.id ?? newEntryId;
  const activeDisplayName = getDisplayEntryName(entryNames[activeItemId] || activeEntry?.entry_name, leafSubtype.name);
  const activeItemName =
    activeDisplayName
    || leafSubtype.name;

  const editorItems: MyGoTwoWebCoverflowItem[] = [
    ...groupEntries.map((entry) => ({
      id: entry.id,
      label: getDisplayEntryName(entryNames[entry.id] || entry.entry_name, leafSubtype.name) || leafSubtype.name,
      previewTitle: getDisplayEntryName(entryNames[entry.id] || entry.entry_name, leafSubtype.name) || leafSubtype.name,
      image: normalizeImageValue(
        resolvedEntryImages[entryImages[entry.id] || entry.image_url || ""]
        || entryImages[entry.id]
        || entry.image_url,
      ),
    })),
    {
      id: newEntryId,
      label: getDisplayEntryName(entryNames[newEntryId]?.trim(), leafSubtype.name) || leafSubtype.name,
      previewTitle: getDisplayEntryName(entryNames[newEntryId]?.trim(), leafSubtype.name) || leafSubtype.name,
      image: normalizeImageValue(resolvedEntryImages[entryImages[newEntryId] || ""] || entryImages[newEntryId]),
    },
  ];

  const activeItemValues = entryDrafts[activeItemId] || defaultFieldValues;
  const activeItemImage =
    normalizeImageValue(entryImages[activeItemId])
    || normalizeImageValue(activeEntry?.image_url)
    || "";

  return (
    <MyGoTwoDesktopBrowser
      pageKey={`entry-browser:${leafSubtype.id}:${currentGroup}`}
      items={editorItems}
      focusedItemId={activeItemId}
      onCommit={(id) => {
        const nextIndex = editorItems.findIndex((item) => item.id === id);
        if (nextIndex < 0) return;
        setActiveEntryIndexByGroup((prev) => ({ ...prev, [currentGroup]: nextIndex }));
      }}
      onActiveIdChange={(id) => {
        const nextIndex = editorItems.findIndex((item) => item.id === id);
        if (nextIndex < 0) return;
        setActiveEntryIndexByGroup((prev) => ({ ...prev, [currentGroup]: nextIndex }));
      }}
      topSlot={
        <button
          type="button"
          aria-label="Go back"
          className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-full border border-white/75 bg-[rgba(255,255,255,0.72)] text-[var(--logo-two-color)] shadow-[0_10px_26px_rgba(20,20,30,0.08)]"
          onClick={onBack}
        >
          <ChevronLeft className="h-5 w-5" />
        </button>
      }
      visibleEachSide={groupEntries.length > 0 ? undefined : 0}
      overlay={
        <div className="flex h-full items-center justify-center px-8 pb-8 pt-16">
          <div
            className="pointer-events-auto w-full max-w-[462px] overflow-hidden rounded-[32px] shadow-[0_18px_34px_rgba(110,117,118,0.22),0_34px_90px_rgba(75,79,79,0.24)]"
            style={{ aspectRatio: "462 / 678" }}
          >
            <MyGoTwoWebProductCard
              subtype={leafSubtype}
              subcategoryName={leafSubcategoryName}
              categoryName={leafCategoryName}
              entryName={activeDisplayName}
              values={activeItemValues}
              imageUrl={activeItemImage}
              saving={saving}
              isEditing={!activeItemId.startsWith(`${newEntryPrefix}::`)}
              onEntryNameChange={(name) => onEntryNameChange(activeItemId, name)}
              onChange={(fieldLabel, value) => onFieldChange(activeItemId, fieldLabel, value)}
              onImageChange={(imageUrl) => onImageChange(activeItemId, imageUrl)}
              onSave={() => onSaveEntry(activeItemId)}
              onDelete={() => onDeleteEntry(activeItemId)}
            />
          </div>
        </div>
      }
      footer={
        <div className="flex flex-wrap items-center justify-center gap-5 pb-2 pt-6">
          <button
            type="button"
            className="inline-flex items-center gap-4 rounded-full border px-8 py-4 text-[22px] leading-none shadow-[0_8px_24px_rgba(20,20,30,0.08)]"
            style={{
              background: "rgba(255,255,255,0.74)",
              borderColor: "rgba(190,176,160,0.58)",
              color: "var(--swatch-teal)",
              fontFamily: "'Jost', sans-serif",
            }}
            onClick={onCreateGroup}
          >
            <span className="text-[24px] font-light">+</span>
            <span className="text-[24px] font-medium tracking-[-0.03em]">New Group</span>
          </button>

          <div
            className="text-[28px] leading-none"
            style={{
              color: "rgba(82,110,125,0.72)",
              fontFamily: "'Cormorant Garamond', serif",
            }}
          >
            {saving ? "Saving..." : `Saving to: ${activeItemName}`}
          </div>
        </div>
      }
    />
  );
}
