import type { Dispatch, SetStateAction } from "react";
import { ChevronLeft } from "lucide-react";
import type { SubtypeItem } from "@/data/templateSubtypes";
import MyGoTwoDesktopPage from "@/platform-ui/web/mygotwo/MyGoTwoDesktopPage";
import type { MyGoTwoWebCoverflowItem } from "@/platform-ui/web/mygotwo/MyGoTwoWebCoverflow";
import MyGoTwoWebCoverflow from "@/platform-ui/web/mygotwo/MyGoTwoWebCoverflow";
import MyGoTwoWebProductCard from "@/platform-ui/web/mygotwo/MyGoTwoWebProductCard";

interface CardEntry {
  id: string;
  user_id: string;
  card_key: string;
  group_name: string;
  entry_name: string;
  field_values: Record<string, string>;
  image_url?: string | null;
  created_at: string;
  updated_at: string;
}

interface MyGoTwoDesktopCardBrowserProps {
  leafSubtype: SubtypeItem;
  leafSubcategoryName?: string;
  leafCategoryName?: string;
  leafImage: string;
  entries: CardEntry[];
  productGroups: string[];
  activeGroup: string;
  setActiveGroup: Dispatch<SetStateAction<string>>;
  focusedEntryIdByGroup: Record<string, string>;
  setFocusedEntryIdByGroup: Dispatch<SetStateAction<Record<string, string>>>;
  entryNames: Record<string, string>;
  entryDrafts: Record<string, Record<string, string>>;
  entryImages: Record<string, string>;
  resolvedEntryImages: Record<string, string>;
  defaultFieldValues: Record<string, string>;
  saving: boolean;
  newEntryPrefix: string;
  normalizeImageValue: (value?: string | null) => string;
  onBack: () => void;
  onEntryNameChange: (itemId: string, value: string) => void;
  onFieldChange: (itemId: string, fieldLabel: string, value: string) => void;
  onImageChange: (itemId: string, imageUrl: string) => void;
  onSaveEntry: (itemId: string) => void;
  onDeleteEntry: (itemId: string) => void;
  onCreateGroup: () => void;
}

function isAutoGeneratedEntryName(name: string | undefined, subtypeName: string) {
  if (!name) return false;
  const escapedSubtypeName = subtypeName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^${escapedSubtypeName}\\s+\\d+$`).test(name.trim());
}

function getDisplayEntryName(name: string | undefined, subtypeName: string) {
  if (!name || isAutoGeneratedEntryName(name, subtypeName)) return "";
  return name;
}

export default function MyGoTwoDesktopCardBrowser({
  leafSubtype,
  leafSubcategoryName,
  leafCategoryName,
  leafImage,
  entries,
  productGroups,
  activeGroup,
  setActiveGroup,
  focusedEntryIdByGroup,
  setFocusedEntryIdByGroup,
  entryNames,
  entryDrafts,
  entryImages,
  resolvedEntryImages,
  defaultFieldValues,
  saving,
  newEntryPrefix,
  normalizeImageValue,
  onBack,
  onEntryNameChange,
  onFieldChange,
  onImageChange,
  onSaveEntry,
  onDeleteEntry,
  onCreateGroup,
}: MyGoTwoDesktopCardBrowserProps) {
  const currentGroup = productGroups.includes(activeGroup) ? activeGroup : productGroups[0] || leafSubtype.name;
  const groupEntries = entries.filter((entry) => entry.group_name === currentGroup);
  const newEntryId = `${newEntryPrefix}::${currentGroup}`;
  const editorItems: MyGoTwoWebCoverflowItem[] = [
    ...groupEntries.map((entry) => ({
      id: entry.id,
      label: getDisplayEntryName(entryNames[entry.id] || entry.entry_name, leafSubtype.name) || leafSubtype.name,
      previewTitle: getDisplayEntryName(entryNames[entry.id] || entry.entry_name, leafSubtype.name) || leafSubtype.name,
      image: normalizeImageValue(
        resolvedEntryImages[entryImages[entry.id] || entry.image_url || ""]
        || entryImages[entry.id]
        || entry.image_url,
      ),
    })),
    {
      id: newEntryId,
      label: getDisplayEntryName(entryNames[newEntryId]?.trim(), leafSubtype.name) || leafSubtype.name,
      previewTitle: getDisplayEntryName(entryNames[newEntryId]?.trim(), leafSubtype.name) || leafSubtype.name,
      image: normalizeImageValue(resolvedEntryImages[entryImages[newEntryId] || ""] || entryImages[newEntryId] || leafImage),
    },
  ];

  const preferredActiveItemId = focusedEntryIdByGroup[currentGroup];
  const activeItemId = editorItems.some((item) => item.id === preferredActiveItemId)
    ? preferredActiveItemId
    : editorItems[0]?.id ?? newEntryId;
  const activeEntry = groupEntries.find((entry) => entry.id === activeItemId) ?? null;
  const activeDisplayName = getDisplayEntryName(entryNames[activeItemId] || activeEntry?.entry_name, leafSubtype.name);
  const activeItemName =
    activeDisplayName
    || leafSubtype.name;

  const activeItemValues = entryDrafts[activeItemId] || defaultFieldValues;
  const activeItemImage =
    normalizeImageValue(resolvedEntryImages[entryImages[activeItemId] || activeEntry?.image_url || ""])
    || normalizeImageValue(entryImages[activeItemId])
    || normalizeImageValue(activeEntry?.image_url)
    || normalizeImageValue(leafImage)
    || "";

  return (
    <MyGoTwoDesktopPage
      topSlot={
        <button
          type="button"
          aria-label="Go back"
          className="inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-full border border-white/75 bg-[rgba(255,255,255,0.72)] text-[var(--logo-two-color)] shadow-[0_10px_26px_rgba(20,20,30,0.08)]"
          onClick={onBack}
        >
          <ChevronLeft className="h-5 w-5" />
        </button>
      }
    >
      <div className="grid h-full min-h-0 gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(400px,462px)]">
        <section className="flex min-h-0 flex-col rounded-[32px] border border-white/60 bg-[rgba(255,255,255,0.28)] px-5 pb-5 pt-16 shadow-[inset_0_1px_0_rgba(255,255,255,0.72),0_18px_42px_rgba(20,20,30,0.08)] backdrop-blur-md">
          <div className="flex flex-wrap items-center gap-3">
            {productGroups.map((groupName) => {
              const isActive = groupName === currentGroup;
              const isSyntheticGroup = /^__product_group_\d+$/.test(groupName);
              const label = isSyntheticGroup ? `Group ${groupName.split("_").pop()}` : groupName;

              return (
                <button
                  key={groupName}
                  type="button"
                  className="rounded-full px-4 py-2 text-[13px] transition-all"
                  style={{
                    fontFamily: "'Jost', sans-serif",
                    background: isActive ? "var(--swatch-teal)" : "rgba(255,255,255,0.6)",
                    color: isActive ? "white" : "var(--swatch-teal)",
                    border: isActive ? "1px solid var(--swatch-teal)" : "1px solid rgba(45,104,112,0.18)",
                  }}
                  onClick={() => setActiveGroup(groupName)}
                >
                  {label}
                </button>
              );
            })}
            <button
              type="button"
              className="rounded-full border border-dashed px-4 py-2 text-[13px]"
              style={{ fontFamily: "'Jost', sans-serif", color: "var(--swatch-teal)", borderColor: "rgba(45,104,112,0.32)" }}
              onClick={onCreateGroup}
            >
              + New Group
            </button>
          </div>

          <div className="mt-4 min-h-0 flex-1">
            <MyGoTwoWebCoverflow
              items={editorItems}
              focusedItemId={activeItemId}
              onCommit={(id) => {
                setFocusedEntryIdByGroup((prev) => ({ ...prev, [currentGroup]: id }));
              }}
              onActiveIdChange={(id) => {
                setFocusedEntryIdByGroup((prev) => ({ ...prev, [currentGroup]: id }));
              }}
              stageHeight="100%"
              visibleEachSide={editorItems.length > 1 ? 2 : 0}
            />
          </div>

          <div className="flex flex-wrap items-center justify-between gap-4 pt-4">
            <div
              className="text-[22px] leading-none"
              style={{
                color: "rgba(82,110,125,0.72)",
                fontFamily: "'Cormorant Garamond', serif",
              }}
            >
              {saving ? "Saving..." : `Editing: ${activeItemName}`}
            </div>
          </div>
        </section>

        <aside className="flex min-h-0 items-center justify-center pb-4 xl:pb-0">
          <div
            className="w-full max-w-[462px] overflow-hidden rounded-[32px] shadow-[0_18px_34px_rgba(110,117,118,0.22),0_34px_90px_rgba(75,79,79,0.24)]"
            style={{ aspectRatio: "462 / 678" }}
          >
            <MyGoTwoWebProductCard
              subtype={leafSubtype}
              subcategoryName={leafSubcategoryName}
              categoryName={leafCategoryName}
              entryName={activeDisplayName}
              values={activeItemValues}
              imageUrl={activeItemImage}
              saving={saving}
              isEditing={!activeItemId.startsWith(`${newEntryPrefix}::`)}
              onEntryNameChange={(name) => onEntryNameChange(activeItemId, name)}
              onChange={(fieldLabel, value) => onFieldChange(activeItemId, fieldLabel, value)}
              onImageChange={(imageUrl) => onImageChange(activeItemId, imageUrl)}
              onSave={() => onSaveEntry(activeItemId)}
              onDelete={() => onDeleteEntry(activeItemId)}
            />
          </div>
        </aside>
      </div>
    </MyGoTwoDesktopPage>
  );
}
